### PR TITLE
Migrate CI to GitHub Actions

### LINKED ISSUE #261: Set new CI up
I do not know what happened to Travis CI, but the last commit which was build seems to be https://github.com/pavouk/lgi/commit/95418635aa8151a516d43166227ea2b9d4c4403f: https://travis-ci.org/github/pavouk/lgi/builds/673164708

The following commit does not have a CI link (the green arrow on the commit page): https://github.com/pavouk/lgi/commit/bdf41c6f883652595a648943f09f61abc11c88c6

This seems like a good reason/excuse to migrate away from Travis CI. I guess GitHub Actions is an obvious alternative, but I am open for suggestions. (Yay for more centralisation! :disappointed: )

(I'm not even sure if I could set Actions up or whether that requires help from @pavouk.

### PR DESCRIPTION
**Pull request by fstirlitz**
I tested this on my local fork and it seems to work well (PR fstirlitz/lgi#1). Disabling Travis entirely (e.g. removing hooks) will have to be done by the repository owner, @pavouk. This will resolve #261.

Other tasks to consider:
- [x] Enable ASan and UBSan in the CI builds

  UBSan has already managed to find one issue. I am not fixing it here, to keep the PR focused only on CI setup.
- [x] Add coverage measurement and tracking

### CODE REVIEW

**Comment by psychon** [comment]
Thanks!

I haven't looked closely into this, but if you don't delete .travis.yml, I could just merge this. However, it does not look like checks were run for this PR...?

**Comment by fstirlitz** [comment]
I think this is because the YAML file doesn’t originate from this repository. You can try pushing the same commit on a branch of this one, start a pull request to merge that branch and see if a run is triggered.

**Comment by fstirlitz** [comment]
It looks like tests on LuaJIT 2.1.0-beta3 crash with a SIGSEGV: maybe it’s their bug, maybe ours. The Travis config looks like it runs tests with the latest git master instead of formal releases, which seems a bit… dangerous? It makes CI builds less deterministic, and therefore kind of defeats the point of CI. Although now that LuaJIT is no longer developed, this is kind of moot.

Also, why even keep Travis config around? It’s not like Travis isn’t going away soon anyway…

**Comment by fstirlitz** [comment]
@psychon Review?

**Comment by psychon** [comment]
> I added coverage reports via Codecov; I am not too sure if that will work, as I have not succeeded at obtaining a full report.

Seems like it did not.

The build after merging this is at https://github.com/lgi-devs/lgi/runs/5738254036?check_suite_focus=true (this link goes to the Lua 5.4 build). This did not upload much to codecov:

```
==> Reading reports
    + ./#usr#include#glib-2.0#glib#gstring.h.gcov bytes=11637
    + ./buffer.c.gcov bytes=32
    + ./#usr#include#x86_64-linux-gnu#bits#string_fortified.h.gcov bytes=6664
    + ./record.c.gcov bytes=32
    + ./core.c.gcov bytes=30
    + ./test_c.c.gcov bytes=32
    + ./#usr#share#gobject-introspection-1.0#tests#regress.c.gcov bytes=266483
    + ./object.c.gcov bytes=32
    + ./callable.c.gcov bytes=34
    + ./gi.c.gcov bytes=28
    + ./marshal.c.gcov bytes=33
```
`bytes=32` sounds like "empty" (or at least "really not much")

Before that, there is also this:
```
Cannot open source file callable.c
Cannot open source file object.c
Cannot open source file gi.c
Cannot open source file buffer.c
Cannot open source file record.c
Cannot open source file marshal.c
Cannot open source file core.c
Cannot open source file test_c.c
```
So... I guess the paths are wrong?

Anyway, once upon a time I fought to get code coverage working in CI, but I do not really want to repeat that, so I'll just ignore this :shrug:

**Comment by fstirlitz** [comment]
Ah. I had trouble finding any error messages. I probably should have specified `working-directory`.

Also, there’s [this](https://github.com/codecov/codecov-action#%EF%B8%8F--deprecration-of-v1=), which I missed completely:

> On February 1, 2022, this version will be fully sunset and no longer function

Maybe measuring coverage manually wouldn’t have been so bad after all…

By the way, if you had performed the merge by rebasing, you could have just backed out the last commit after seeing it doesn’t work.

**Comment by psychon** [comment]
> By the way, if you had performed the merge by rebasing, you could have just backed out the last commit after seeing it doesn’t work.

I can also force-push that commit away with a merge commit. And I think working CI and non-working coverage is better than no CI. So again, thanks for providing this!

**Pull request merged**
