### PR TITLE
[CI] Support Lua 5.4

### PR DESCRIPTION
**Pull request by Aire-One**
Hello,

Following recent discussions from #247, let's add support for Lua 5.4 in the CI to make sure everything is ready for LGI to supports this Lua version.

### CODE REVIEW

**Review by Elv13 — APPROVED** [review]

**Comment by Aire-One** [comment]
Hm... I guess LGI has the same issue we had with Travis at the awesomewm repository.

What's the next step @psychon? Should we move the CI to GitHub Actions?

**Comment by Elv13** [comment]
Or ask make you admin here and ask Travis for some Free open source credits. It's not like this repo has these huge burst of PRs/builds like AwesomeWM has when I am active (which is the reason I was paying, I was depleting the credits)

**Comment by psychon** [comment]
> What's the next step @psychon? Should we move the CI to GitHub Actions?

#261 :shrug: 

> Or ask @psychon to make you admin here 

Feel free to ask. However, I am not an admin here and thus cannot do that.

**Comment by psychon** [comment]
Somehow I doubt that this PR would build on Travis. Looking at `.travis.yml`, there is special magic to handle lua5.3 and luajit-2.0. Everything else just installs `lib${LUANAME}-dev` and `${LUANAME}`. Since this specifies `dist: trusty`, I somehow doubt that there is a suitable package available. However, `packages.ubuntu.com` apparently never heard about trusty and thus I cannot check. Since it's "End of standard support" for almost two years now.... yeah... I doubt that works.

**Comment by Aire-One** [comment]
Following the recent merge of the new CI with GitHub Actions with Lua 5.4 is already cared of, I close this PR.

**Pull request closed without merging**
